//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Alumno_Asignatura = new HashSet<Alumno_Asignatura>();
        }
    
        public int Id { get; set; }
        public string carne { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
        public System.DateTime fecha_proceso { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public int id_carrera { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno_Asignatura> Alumno_Asignatura { get; set; }
        public virtual Carrera Carrera { get; set; }
    }
}
